### ISSUE TITLE
定时抢座的程序

### ISSUE THREAD

**Issue by xxjyyyd** [yuzheng14/tracient-book#10]
楼主有定时抢座程序嘛跪求

**Comment by yuzheng14** [comment]
程序内置定时功能啊

**Comment by xxjyyyd** [comment]
里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗

**Comment by xxjyyyd** [comment]
> 



> 程序内置定时功能啊

里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗

**Comment by yuzheng14** [comment]
> > 
> 
> > 程序内置定时功能啊
> 
> 里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗

捡漏也是有定时的啊，捡漏里面调用的 wait_for_reserve 函数里面有定时，默认就是7点

**Comment by xxjyyyd** [comment]
> > > 
> > 
> > 
> > > 程序内置定时功能啊
> > 
> > 
> > 里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗
> 
> 捡漏也是有定时的啊，捡漏里面调用的 wait_for_reserve 函数里面有定时，默认就是7点

那捡漏我看是扫描整个楼层，想要具体一个位置怎么修改😭

**Comment by yuzheng14** [comment]
> > > > 
> > > 
> > > 
> > > > 程序内置定时功能啊
> > > 
> > > 
> > > 里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗
> > 
> > 
> > 捡漏也是有定时的啊，捡漏里面调用的 wait_for_reserve 函数里面有定时，默认就是7点
> 
> 那捡漏我看是扫描整个楼层，想要具体一个位置怎么修改😭

因为我们学校图书馆不够用，等捡漏就没啥座位了，所以最多能指定常用楼层，不支持具体座位。
想改的话就改 pass_reserve 函数及相关调用链，注释写的很清楚具体看注释

**Comment by xxjyyyd** [comment]
可以帮改一下吗大佬孩子实在看不懂

**Comment by xxjyyyd** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > 程序内置定时功能啊
> > > > 
> > > > 
> > > > 里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗
> > > 
> > > 
> > > 捡漏也是有定时的啊，捡漏里面调用的 wait_for_reserve 函数里面有定时，默认就是7点
> > 
> > 
> > 那捡漏我看是扫描整个楼层，想要具体一个位置怎么修改😭
> 
> 因为我们学校图书馆不够用，等捡漏就没啥座位了，所以最多能指定常用楼层，不支持具体座位。 想改的话就改 pass_reserve 函数及相关调用链，注释写的很清楚具体看注释

可以帮忙改一下吗孩子实在看不懂

**Comment by yuzheng14** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > > 程序内置定时功能啊
> > > > > 
> > > > > 
> > > > > 里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗
> > > > 
> > > > 
> > > > 捡漏也是有定时的啊，捡漏里面调用的 wait_for_reserve 函数里面有定时，默认就是7点
> > > 
> > > 
> > > 那捡漏我看是扫描整个楼层，想要具体一个位置怎么修改😭
> > 
> > 
> > 因为我们学校图书馆不够用，等捡漏就没啥座位了，所以最多能指定常用楼层，不支持具体座位。 想改的话就改 pass_reserve 函数及相关调用链，注释写的很清楚具体看注释
> 
> 可以帮忙改一下吗孩子实在看不懂

最近忙着找工作，没时间

**Comment by xxjyyyd** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > > 程序内置定时功能啊
> > > > > > 
> > > > > > 
> > > > > > 里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗
> > > > > 
> > > > > 
> > > > > 捡漏也是有定时的啊，捡漏里面调用的 wait_for_reserve 函数里面有定时，默认就是7点
> > > > 
> > > > 
> > > > 那捡漏我看是扫描整个楼层，想要具体一个位置怎么修改😭
> > > 
> > > 
> > > 因为我们学校图书馆不够用，等捡漏就没啥座位了，所以最多能指定常用楼层，不支持具体座位。 想改的话就改 pass_reserve 函数及相关调用链，注释写的很清楚具体看注释
> > 
> > 
> > 可以帮忙改一下吗孩子实在看不懂
> 
> 最近忙着找工作，没时间

有偿可以吗😭😭😭

**Comment by yuzheng14** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > > 程序内置定时功能啊
> > > > > > > 
> > > > > > > 
> > > > > > > 里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗
> > > > > > 
> > > > > > 
> > > > > > 捡漏也是有定时的啊，捡漏里面调用的 wait_for_reserve 函数里面有定时，默认就是7点
> > > > > 
> > > > > 
> > > > > 那捡漏我看是扫描整个楼层，想要具体一个位置怎么修改😭
> > > > 
> > > > 
> > > > 因为我们学校图书馆不够用，等捡漏就没啥座位了，所以最多能指定常用楼层，不支持具体座位。 想改的话就改 pass_reserve 函数及相关调用链，注释写的很清楚具体看注释
> > > 
> > > 
> > > 可以帮忙改一下吗孩子实在看不懂
> > 
> > 
> > 最近忙着找工作，没时间
> 
> 有偿可以吗😭😭😭

主要是没时间，一堆笔试，还有可能有面试，然后还要背面经八股文之类的

**Comment by xxjyyyd** [comment]
> > > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > > 程序内置定时功能啊
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 里面不是捡漏吗想要实现七点准时抢一个座位也可以实现吗
> > > > > > > 
> > > > > > > 
> > > > > > > 捡漏也是有定时的啊，捡漏里面调用的 wait_for_reserve 函数里面有定时，默认就是7点
> > > > > > 
> > > > > > 
> > > > > > 那捡漏我看是扫描整个楼层，想要具体一个位置怎么修改😭
> > > > > 
> > > > > 
> > > > > 因为我们学校图书馆不够用，等捡漏就没啥座位了，所以最多能指定常用楼层，不支持具体座位。 想改的话就改 pass_reserve 函数及相关调用链，注释写的很清楚具体看注释
> > > > 
> > > > 
> > > > 可以帮忙改一下吗孩子实在看不懂
> > > 
> > > 
> > > 最近忙着找工作，没时间
> > 
> > 
> > 有偿可以吗😭😭😭
> 
> 主要是没时间，一堆笔试，还有可能有面试，然后还要背面经八股文之类的

好的吧，我明天再试试手抢抢不上就放弃了

**Comment by lovelearn123123** [comment]
@xxjyyyd 老哥，加个好友
