### ISSUE TITLE
救命呀

### ISSUE THREAD

**Issue by lovelearn123123** [yuzheng14/tracient-book#11]
不会用，好难，哭了😭

**Comment by yuzheng14** [comment]
使用就用 pip 安装这个库，然后用里面那四个函数，docstring 我写的很完善，参考着用就行了

**Comment by codesbykhalil** [comment]
大佬，需要修改什么吗，还是说只用传cookie

**Comment by lovelearn123123** [comment]
docstring在哪呢，看不懂在哪改

**Comment by yuzheng14** [comment]
> 大佬，需要修改什么吗，还是说只用传cookie

需要根据自己学校情况修改相关逻辑

**Comment by yuzheng14** [comment]
> docstring在哪呢，看不懂在哪改

函数体下面都有，ide也会有提示的

**Comment by lovelearn123123** [comment]
![J2K)3$1FY}8YWR7~2C2P@RK](https://user-images.githubusercontent.com/103545146/197743885-8467a0be-7f27-4f47-bf27-58df7736ced1.png)
这是啥情况呀
