### ISSUE TITLE
关于cookie保活

### ISSUE THREAD

**Issue by JonahLee1999** [yuzheng14/tracient-book#5]
老哥您好，我想请教一下新版的cookie怎么保活呢，尝试过像以前一样刷首页但是仍然会过期。感谢您的时间。

**Comment by yuzheng14** [comment]
1.9及之前是可用的，1.9之后我们学校换系统了我也没法继续开发了。
能用的时候cookie失效时间是半小时至一小时之间。
按理来说应该不会频繁更换cookie，否则可能会导致选座的时候突然蹦出来登录验证。
建议自行抓包看看怎么回事。
