### ISSUE TITLE
怎么用

### ISSUE THREAD

**Issue by 2020leslie** [yuzheng14/tracient-book#6]
请问怎么实现微信抓包，传入参数和一些需要根据特定学校改变的参数

**Comment by yuzheng14** [comment]
我是电脑用的fiddler，手机用的httpcanary
请根据抓包信息自行修改相关部分以适配自己学校

**Comment by yuzheng14** [comment]
根据我抓包得到的信息，学校应该是通过json文件里的schid识别的

**Comment by 2020leslie** [comment]
好的，感谢回复

**Comment by 2020leslie** [comment]
请问，方不方便给个QQ，想问一些问题

**Comment by yuzheng14** [comment]
422450117
