### ISSUE TITLE
参数获取

### ISSUE THREAD

**Issue by 56luffy** [yuzheng14/tracient-book#8]
想仿照https://zhuanlan.zhihu.com/p/260814052进行专属座位抢座,图书馆关闭了预约功能,但是需要js返回的参数,https://blog.csdn.net/RenjiaLu9527/article/details/96843605,能不能加上这个的实现或者教我一下

**Comment by yuzheng14** [comment]
第一个没看懂什么意思
第二个我们学校用的我去图书馆公众号参数校验和所给不一样，我写的版本我们学校可以完美运行

**Comment by chenmozero** [comment]
大佬，我想问下如果要用的话需要更改哪些地方，换成我们学校和我自己的信息呢

**Comment by yuzheng14** [comment]
根据学校定制程度不同要改的也不同，最少要更改抢座地址和cookie参数，其余根据自己学校实际情况进行更改
