### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ysw774977** [yuzheng14/tracient-book#9]

**Comment by ysw774977** [comment]
是明日预约那边排队的WebSocket

**Comment by yuzheng14** [comment]
我们学校换系统了，没法测试啥的了

**Comment by yuzheng14** [comment]
我用的websocket的包不怎么好用，我也不大会连接websocket

**Comment by ysw774977** [comment]
可以在我去图书馆切换学校，北京交通大学、南昌师范学院啥啥的都可以，大佬如果最近忙的话就算了吧 呜呜

**Comment by yuzheng14** [comment]
考研也没太有时间，这个程序基本上都是我边查边写的，你查查资料写写看看叭

**Comment by ysw774977** [comment]
谢谢大佬 大佬考研顺利~

**Comment by 2020leslie** [comment]
同学，我也在研究这个项目，可以加个联系方式私聊一下

**Comment by ysw774977** [comment]
呜呜 谢谢大佬 我已经搞定啦！！！

**Comment by 2020leslie** [comment]
同学怎么改的，能告诉一下吗

**Comment by JonahLee1999** [comment]
> 呜呜 谢谢大佬 我已经搞定啦！！！

你好，方便请教一下吗，同样也在学习这个项目😭

**Comment by 56luffy** [comment]
> 呜呜 谢谢大佬 我已经搞定啦！！！

能问一下明日预约的问题吗,它提示我需要先排队,但是我们学校的明日预约被关闭了无法得到这个排队的json

**Comment by yuzheng14** [comment]
> > 呜呜 谢谢大佬 我已经搞定啦！！！
> 
> 能问一下明日预约的问题吗,它提示我需要先排队,但是我们学校的明日预约被关闭了无法得到这个排队的json

那就只能看看别的学校的json了

**Comment by ZiuChen** [comment]
BJTU 明日预约不可用：平台换用了新的排队机制

1. POST `prereserveCheckMsg`
2. Websockets `wss://wechat.v2.traceint.com/ws?ns=prereserve/queue` 排队

使用此项目明日预约时，代码执行到 `queue_init()` 时，服务器返回的 `get_step_response` 为：

```json
{
    "errors": [
        {
            "msg": "客户端程序版本太旧，请点击右上角(...)刷新",
            "code": 1
        },
        {
            "msg": "客户端程序版本太旧，请点击右上角(...)刷新",
            "code": 1
        },
        {
            "msg": "客户端程序版本太旧，请点击右上角(...)刷新",
            "code": 1
        }
    ],
    "data": {
        "userAuth": {
            "prereserve": {
                "getStep": None,
                "queeUrl": None,
                "successUrl": "https: //wechat.v2.traceint.com/quee/success?sid=0000000&schId=00&t=xxxxxxxxxxxxxx",
                "endTime": None
            }
        }
    }
}
```

这导致取到的 `need_captcha`  `need_queue` `ws_url` 分别为 `False` `False` `None`

未正确完成排队

**Comment by yuzheng14** [comment]
> BJTU 明日预约不可用：平台换用了新的排队机制
> 
> 1. POST `prereserveCheckMsg`
> 2. Websockets `wss://wechat.v2.traceint.com/ws?ns=prereserve/queue` 排队
> 
> 使用此项目明日预约时，代码执行到 `queue_init()` 时，服务器返回的 `get_step_response` 为：
> 
> ```json
> {
>     "errors": [
>         {
>             "msg": "客户端程序版本太旧，请点击右上角(...)刷新",
>             "code": 1
>         },
>         {
>             "msg": "客户端程序版本太旧，请点击右上角(...)刷新",
>             "code": 1
>         },
>         {
>             "msg": "客户端程序版本太旧，请点击右上角(...)刷新",
>             "code": 1
>         }
>     ],
>     "data": {
>         "userAuth": {
>             "prereserve": {
>                 "getStep": None,
>                 "queeUrl": None,
>                 "successUrl": "https: //wechat.v2.traceint.com/quee/success?sid=0000000&schId=00&t=xxxxxxxxxxxxxx",
>                 "endTime": None
>             }
>         }
>     }
> }
> ```
> 
> 这导致取到的 `need_captcha` `need_queue` `ws_url` 分别为 `False` `False` `None`
> 
> 未正确完成排队

我们学校换平台了，请自行抓包分析解决
